### ISSUE TITLE
Improve LICENSE Discovery

### ISSUE THREAD

**Issue by AidanKelley** [KnowledgeCaptureAndDiscovery/somef#100]
Sometimes, as with WIDOCO, there is a license but SoMEF does not find it. This is because, in WIDOCO it has it's own LICENSE file but it was not a license that was added through GitHub, so it does not show up in the GitHub metadata. Since SoMEF gets LICENSE from the GitHub metadata, it does not find the license. This makes it look like the code has no license.

**Comment by dgarijo** [comment]
This can also be done when cloning the repo, and looking if there are files that match the pattern LICENSE.*
