### ISSUE TITLE
What URL should we give for issue tracker? IssueTracker

### ISSUE THREAD

**Issue by AidanKelley** [KnowledgeCaptureAndDiscovery/somef#131]
Currently, somef outputs a URL like this:

```https://api.github.com/repos/dgarijo/Widoco/issues{/number}```

for the ```issueTracker``` value.

Should it instead output something like

```https://github.com/dgarijo/Widoco/issues```

?

**Comment by dgarijo** [comment]
I thought about this. However, I added no further changes because this is what is returned by the GitHub API. 

Do you think we should change it?

**Comment by AidanKelley** [comment]
I changed it to the latter option when outputting to codemeta because it looks like that is what they wanted. I do think we should change it, as the first result isn't exactly "machine readable". If you try to blindly access that URL, it is an error, because ```{number}``` needs to be filled in.

**Comment by dgarijo** [comment]
Fair enough. Closing the issue then
