### ISSUE TITLE
Rate limitations due to GitHub API

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/somef#288]
I would like to dig in further if we can use somef even if a rate limitation from GitHub is met.

**Comment by dgarijo** [comment]
We should make sure that the token gets recognized. I don't think there are means now to test this. As a result you never know whether you are going to reach a limitation

**Comment by dgarijo** [comment]
I am raising the importance of this issue. This is slowing down related projects:
- Is there a way of running somef without depending on the API rate limitation? (i.e., we don't retrieve metadata from the API, we just download)
- GitHub API has gone through some changes. Are we doing the login correctly? Is there a way we can test this (it [looks](https://docs.github.com/en/rest/reference/rate-limit#get-rate-limit-status-for-the-authenticated-user--code-samples) there are some ways of testing this). 
- 
I had a look, but even after log in, it tells me my `core` api is 60, which means I can only process 60 repositories. Instead, I should be able to retrieve data from 5000.

**Comment by ma-garcia** [comment]
Reduced calls to API from 5 per repository to 3. There is no chance to reduce more the call to the API due to the date we have to collect from GitHub API.

Also added messages with information regarding the rate limit remaining and the rate limit reset.

**Comment by dgarijo** [comment]
Awesome thanks!
