### ISSUE TITLE
oeg-upm repos on which somef fails 

### ISSUE THREAD

**Issue by dakixr** [KnowledgeCaptureAndDiscovery/somef#355]
I am using 3.10.2 and the latest release from PyPI.

https://github.com/oeg-upm/auroral-website
https://github.com/oeg-upm/bimerr-core
https://github.com/oeg-upm/cogito-kgg-module
https://github.com/oeg-upm/cogito-website
https://github.com/oeg-upm/DIoT
https://github.com/oeg-upm/easytv-annotator-webservice
https://github.com/oeg-upm/easytv-semantic-annotator
https://github.com/oeg-upm/helio-framework
https://github.com/oeg-upm/helio-materialiser
https://github.com/oeg-upm/helio-publisher
https://github.com/oeg-upm/IVHackathonOpenDataCaceres-UPM
https://github.com/oeg-upm/JSONPath-to-SPARQL
https://github.com/oeg-upm/LabSensingArduino
https://github.com/oeg-upm/mappingpedia-contents-test
https://github.com/oeg-upm/mappingpedia-engine
https://github.com/oeg-upm/mappingpedia-engine-executions
https://github.com/oeg-upm/mappingpedia-engine-executions-ws
https://github.com/oeg-upm/mappingpedia-engine-mappings
https://github.com/oeg-upm/Solidity-ontology
https://github.com/oeg-upm/sprint
https://github.com/oeg-upm/t5-spanish-news-summarization

Successfully extracted metadata from (216/237) repositories.

**Comment by dakixr** [comment]
3.10.2 refers to the Python version

**Comment by dgarijo** [comment]
We have tested Somef on Python 3.9. Pls  make sure you use that version for
the moment.

**Comment by dgarijo** [comment]
I tested `https://github.com/oeg-upm/cogito-kgg-module` and indeed fails with Python 3.9. @ma-garcia please have a look, as these look like readmes with little info that we should definitely test!

**Comment by ma-garcia** [comment]
Most of the errors were raised because of so little content on README.md files. https://github.com/oeg-upm/easytv-semantic-annotator is highly recommended not to be tested using the repository url option because the zip file is up to 1.5 GB.
