### ISSUE TITLE
Add which OS somef has been tested with

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/somef#364]
We have tested somef in Unix and MacOS. @ma-garcia  did you test in Windows? I think there is an encoding error that we may have to look at. In the meantime, we should add to readme only the OS we know we support.

**Comment by ma-garcia** [comment]
The following text has been added to "Requirements" section at README.md: "SOMEF has been tested on Unix, MacOS and Windows Microsoft operating systems"
