### ISSUE TITLE
pip install in windows gives a UnicodeDecodeError

### ISSUE THREAD

**Issue by MarcoAS99** [KnowledgeCaptureAndDiscovery/somef#365]
From Somef 0.7.0 onward on Windows when installing or upgrading Somef to the latest version it gives a UnicodeError has can be seen in the following screenshot
![image](https://user-images.githubusercontent.com/56512850/155850680-c2b44927-93cc-4e6b-afdf-5ab2197e9a48.png)

**Comment by dgarijo** [comment]
This looks like a pip encoding error when uploading the package. We'll have to look it up.
In the meantime, I recommend using the Docker image, or executing in Unix/MacOs.
@ma-garcia you work in Windows. Did you face similar issues?

**Comment by dgarijo** [comment]
@MarcoAS99 please test the newer version of somef, which fixes this. Please reopen the issue if there are any problems
