### ISSUE TITLE
Duplicate classification results

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/somef#379]
I tried somef on https://github.com/oeg-upm/AI4EU_raidologist

And I get duplicate results:

![Screenshot from 2022-03-12 12-14-55](https://user-images.githubusercontent.com/1520666/158015853-2979b3c6-12ca-4cf8-968c-ef1e3b168861.png)

Why does this happen?

**Comment by ma-garcia** [comment]
This issue has been solved in the last commit of the code
