### ISSUE TITLE
Somef misses some Dockerfiles

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/somef#389]
In https://github.com/oeg-upm/wot-hive/tree/main/docker/auroral-hive

somef does not seem to detect any dockerfiles, but there is one.

**Comment by ma-garcia** [comment]
Unable to reproduce this issue. With the latest code, two dockerfiles are detected: 'https://raw.githubusercontent.com/oeg-upm/wot-hive/main/docker/auroral-hive/Dockerfile' and 'https://raw.githubusercontent.com/oeg-upm/wot-hive/main/docker/fuseki/Dockerfile'
