### ISSUE TITLE
Field "repoStatus" comes with no confidence value

### ISSUE THREAD

**Issue by Vitoriox** [KnowledgeCaptureAndDiscovery/somef#398]
The field named "repoStatus" doesn't have confidence value like the other fields retrieved by SOMEF.

![Captura de pantalla de 2022-03-28 16-43-30](https://user-images.githubusercontent.com/59898208/160423885-cf7a18fa-331b-4d73-ae3a-e840f61c3665.png)

**Comment by dgarijo** [comment]
Yep, this went over our heads :S
