### ISSUE TITLE
There are 2 ack fields

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/somef#445]
We have acknowledgment (header analsysis) and acknowledgements (file).
Why are they not the same field?

**Comment by ma-garcia** [comment]
Because this field can be identified via header analysis, if it's part of the README text, or via file exploration, if there is a file called "ACKNOWLEDGMENT". That's why there are two different fields.

**Comment by dgarijo** [comment]
But that is why we have the "technique", to identify how the value of the field was obtained.
They are the same field, and I think these two fields should be merged.  This is what happens for other fields like documentation

**Comment by dgarijo** [comment]
Let's keep `acknowledgement` as a field, merging `acknowledgements` into it

**Comment by dgarijo** [comment]
And acknowledgement is a text field.
