### ISSUE TITLE
Weird Behaviour within Citation

### ISSUE THREAD

**Issue by Str3am786** [KnowledgeCaptureAndDiscovery/somef#554]
While preforming a description of the SOMEF repository, it will extract multiple CFF files, with confidence of 1, using the file_exploration technique. This might be due to the /tests/ directory containing CFF files.

There might be a need  to prioritise those within the root directory of the repository, or create a distinction between those correlated to the repository properties and those which are not.

Example extract of somef json: 
![Screenshot from 2023-02-28 15-48-05](https://user-images.githubusercontent.com/74185618/221888792-e7bdd688-9b00-4c91-a7f8-d97aba38c7d7.png)

**Comment by dgarijo** [comment]
This is a bug. The outmost CFF should be the one returned. This was fixed for licenses and readmes, but maybe it was skipped for CFF files.

**Comment by dgarijo** [comment]
This is now fixed
