### ISSUE TITLE
Change Python default version to 3.10

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/somef#587]
After changing to the newer versions of scikit learn, this is the version that seems to work best for `somef`

**Comment by tpronk** [comment]
A word of caution: When installing `somef` on my Windows 10 device, I got the error message below when using Python 3.10, but when using Python 3.9, the installation went smooth

`No module named 'numpy.distutils._msvccompiler' in numpy.distutils`

**Comment by dgarijo** [comment]
Thanks! This issue is not a priority at the moment. I am currently running `somef` with Python 3.10, but it's a Unix system. Will have to have a look

**Comment by dgarijo** [comment]
I see more people are running into issues with 3.10. Will have a look to address them

**Comment by dgarijo** [comment]
We have now tested the tool in Windows and Unix with 3.10, successfully. Also, new Docker images support Python 3.10. Closing!
