### ISSUE TITLE
Using SOMEF with a GitHub token stored in a environment variable

### ISSUE THREAD

**Issue by tpronk** [KnowledgeCaptureAndDiscovery/somef#591]
Hi!

I'm using SOMEF as a module in a Python workflow. In this workflow, I extract software management metadata from our organization; quite similar to a [paper you published recently](https://ceur-ws.org/Vol-3526/paper-09.pdf). I like to keep all my secrets (such as GitHub tokens) in environment variables, but currently, SOMEF seems only to be able to process such tokens via a config file.

Hence, this issue. I'd like to have the option to obtain that token from the environment. If you're OK with it, I could try implementing it myself, in which case I could use some guidelines to ensure my edits fit your overarching design/philosophy.

Best, Thomas

**Comment by dgarijo** [comment]
Hello,
This request makes sense. Happy to accept a pull request :) please send it
to the develop branch.
The configuration.py is probably where you want to do your edits.
Thanks in advance!

**Comment by tpronk** [comment]
My pleasure!

I was testing things using a private repo, but some functions fail with errors like this...
```
Error: Archive request failed with HTTP 404
  File "D:\CLOUD\GitHub\tpronk\somef\src\somef\process_repository.py", line 531, in download_github_files
    sys.exit(f"Error: Archive request failed with HTTP {repo_download.status_code}")
  File "D:\CLOUD\GitHub\tpronk\somef\src\somef\process_repository.py", line 498, in download_repository_files
    return download_github_files(target_dir, owner, repo_name, default_branch)
  File "D:\CLOUD\GitHub\tpronk\somef\src\somef\somef_cli.py", line 67, in cli_get_data
    local_folder = process_repository.download_repository_files(owner, repo_name, def_branch, repo_type,
  File "D:\CLOUD\GitHub\tpronk\somef\src\01.scrape.py", line 60, in <module>
    somef_data = somef_cli.cli_get_data(
SystemExit: Error: Archive request failed with HTTP 404
```

Functions like `load_online_repository_metadata` do succeed, which I guess is because in this function, all calls to the GitHub REST API pass the authorization token via `rate_limit_get`. I think I could fix this by having cases like `download_github_files` pass the authorization token too.

**Comment by tpronk** [comment]
Hey @dgarijo, got a draft PR ready (#592). Before I continue testing: what do you think of the approach I took? (see PR description). If OK in your book, I'll try to wrap it up next week

**Comment by dgarijo** [comment]
Hi @tpronk,
thanks for drafting the PR! Is it finished? The `cli_get_data` method should be called in the main CLI no? 
It looks ok by my book :) Maybe passing down the auth token could be avoided by writing it in the config file from the very beginning, but I guess that we would have to delete it if you don't want the program to reuse it down the line.

The only thing I would like to clarify in some of the functions is that the GitHub authorization token is only used if the repository type is GitHub, not GitLab. If you think the same type of method can apply to GitLab, then we may call it `Authorization token` directly.

Please when you do the PR, do it against the `develop` branch. That's the most updated version of the tool.
Thanks in advance!

**Comment by dgarijo** [comment]
Ok, merged in #591 (thanks!) Will close the issue when I do a release. Also, we need some additional doc in the readme stating that it's possible to do this

**Comment by dgarijo** [comment]
TO DO: Expand the ability to run this through CLI (right now the authorization has been added only in a lib)

**Comment by dgarijo** [comment]
Added in main. I plan a new package release in the next few days. I hope the upgrade for pandas does not bring incompatibilities
