### ISSUE TITLE
Somef gets stuck on this repo

### ISSUE THREAD

**Issue by Str3am786** [KnowledgeCaptureAndDiscovery/somef#601]
Both running with and without classifiers somef gets stuck more than 3 minutes (RSEF timeout) while evaluating this repo: 
https://github.com/hpparvi/PyTransit

**Comment by dgarijo** [comment]
After latest pushes, SOMEF does not get stuck and produces a JSON file successfully

**Comment by dgarijo** [comment]
Will be addressed in the next release (code is there)
