### ISSUE TITLE
SOMEF does not clean up headers properly before the header analysis

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/somef#61]
Example repositories:

- https://github.com/mintproject/droughtIndices
- https://github.com/mintproject/FloodSeverityIndex

These repositories have a `requirements` section that is not read properly. It looks like it's because there are HTML tags that are not cleaned up in the header.

**Comment by dgarijo** [comment]
This may help: https://stackoverflow.com/questions/9662346/python-code-to-remove-html-tags-from-a-string

**Comment by vmdiwanji** [comment]
Added to the package
