### ISSUE TITLE
Installation problem in local machine

### ISSUE THREAD

**Issue by Aidajafarbigloo** [KnowledgeCaptureAndDiscovery/somef#621]
I attempted to install the software on a Windows 10 machine following the provided installation instructions. However, I encountered an error during the installation process. The installation process failed at installing 'numpy' step, even I tried to install packages one by one, but at the end could not reach the functionality. Also I tried other recommended ways.

**Comment by dgarijo** [comment]
@Aidajafarbigloo 
We are currently in the process of updating installation instructions for release 0.9.5. Which Python version are you using?
Also, if you don't provide information on the errors, it's very difficult to help you :(

I suggest trying everything with Python 10 in a Unix based environment. 
From now on, Windows will be supported through Docker.

We are also in the process of creating a stable poetry environment for the tool. Will be there in the next release.

If you want to install somef in Windows without Docker, I suggest version 0.9.4: https://github.com/KnowledgeCaptureAndDiscovery/somef/releases/tag/0.9.4, on Python 3.9

**Comment by Aidajafarbigloo** [comment]
@dgarijo 
I appreciate your response.

I tried the installation on three different windows based systems, and I used virtual env. I'm not using Docker.

My Python version is: Python 3.12.1

In case of using this way of installation: "pip install Somef" I face this error:
![image](https://github.com/KnowledgeCaptureAndDiscovery/somef/assets/143706305/639862df-955a-43d0-9519-a88c980221fd)
![image](https://github.com/KnowledgeCaptureAndDiscovery/somef/assets/143706305/9930c44f-2fce-42f9-afe5-0510d3a483f9)

Also this error: 

packages\setuptools\__init__.py", line 10, in <module> 
    import distutils.core 
ModuleNotFoundError: No module named 'distutils'

I tried to troubleshoot this error, however, it could not be solved.

And in case installing all the requirements one by one without the recommended version, "somef" command is not functioning.

**Comment by dgarijo** [comment]
Hello,
There are multiple potential issues.
First, we have not yet tested somef in Python 3.12. for now, we have tested
in 3.9 (which we are deprecating soon), 3.10( testing) and 3.11 (testing).
Python 3.12 and 3.11 are now in bug fixing status, so we can't guarantee
conformance yet.

Second, I do not have a testing environment for windows, we would have to
set up GitHub actions. It may happen that distillutils is not yet released
for that python version.

In your case, I would recommend 1) running through Docker or 2) downgrade
to Python 3.9, which has been tested in Windows. You can do this with a
conda environment.

We'll try support soon in Windows for python 3.10 and 3.11, sorry for the
inconvenience.

**Comment by Aidajafarbigloo** [comment]
Hello,

I went through all the steps as you explained, but still I can't run the project.

` 'somef' is not recognized as an internal or external command,operable program or batch file. `

![image](https://github.com/KnowledgeCaptureAndDiscovery/somef/assets/143706305/1e40b927-86a5-4343-95fd-a81299bd9368)

**Comment by dgarijo** [comment]
@Aidajafarbigloo in that screenshot I only see that somef is not installed. You don't show the python version or the error you got when installing the tool.

Also, please try running through Docker. It may be the easiest way for you to set up the tool

**Comment by dgarijo** [comment]
I have planned a new release for Feb 2024. I hope that one helps fixes some of the problems you are facing (I can't do it before due to some urgent deadlines)

**Comment by Aidajafarbigloo** [comment]
Hello @dgarijo ,

Thank you.
I did all the steps again.
- Python 3.9
- Somef version 0.9.4
- through Docker
- Without using virtual environment

Finally I could use it.

![image](https://github.com/KnowledgeCaptureAndDiscovery/somef/assets/143706305/33e534a9-44b6-47a2-bcae-75e6bc73632f)
![image](https://github.com/KnowledgeCaptureAndDiscovery/somef/assets/143706305/05a542aa-d269-4eb3-80e4-e3a47b154c0a)

I tried different random URLs, just I cannot find the result **test.json** ! 

![image](https://github.com/KnowledgeCaptureAndDiscovery/somef/assets/143706305/695ab27c-359d-4641-b660-6be9c7577a05)

**Comment by dgarijo** [comment]
You generated the test.json file, inside the container, you need to mount a volume in the container and get the JSON file. In a way, Docker starts a virtual machine, and the volume is like the "pen drive" you stick into it to retrieve your data. We provided some instructions in https://github.com/KnowledgeCaptureAndDiscovery/somef#installing-through-docker

Basically:  `docker run -it --rm -v $PWD/:/out kcapd/somef /bin/bash`, where $PWD should be a path to a locar folder and /out is the folder inside the container. if you cd in that folder and you run somef, the results will appear in your output folder.

Alternatively, you can explore if you can access the files inside the container from the docker desktop application. I have not tried this myself.

I hope this helps. Docker may seem a little challenging at first, but it really helps running many programs in the long run.

Btw, I ran somef in the repo you were attempting and I got this JSON files: [out.json](https://github.com/KnowledgeCaptureAndDiscovery/somef/files/14050952/out.json) Note that the supervised classifiers have variable quality, you  may filter with a higher threshold.

**Comment by Aidajafarbigloo** [comment]
Got it, thanks.
I could reach the outputs in this way, is it correct? you mean this?
I mounted a volume "e.g. out" in the container, but couldn't reach the output through that. 

![image](https://github.com/KnowledgeCaptureAndDiscovery/somef/assets/143706305/218b0e61-8b4d-47f6-b2ea-a87bfda906bd)


 Can I save the output in my IDE?

**Comment by dgarijo** [comment]
If you move `out.json` to the `out` folder, you should see it in the folder in your local machine.
For example, let's say that I mount the volume in my local machine C:/Desktop/test  as :/out in Docker. Then whatever you put in `/out` you'll see in `test`. For more info I recommend having a look at volumes in the Docker doc.

**Comment by Aidajafarbigloo** [comment]
@dgarijo 
Hello,

Are you planning to provide API for somef?

**Comment by dgarijo** [comment]
API as in a service? The tool can be imported as a library and use the current functions.

**Comment by Aidajafarbigloo** [comment]
Hello @dgarijo ,

I successfully installed version 0.9.4 of 'somef' package from PyPI on Windows os, without utilizing Docker. This installation was in a Python virtual environment running Python version 3.9.0. The outcome presents in my project directory. 
:)

**Comment by dgarijo** [comment]
Excellent! I will close the issue then.
