### ISSUE TITLE
"readme" in CodeMeta format

### ISSUE THREAD

**Issue by Aidajafarbigloo** [KnowledgeCaptureAndDiscovery/somef#636]
Hello @dgarijo 

In the Codemeta output of Somef, readme is a URL linking to the raw content: "https://raw.githubusercontent.com/dgarijo/Widoco/master/README.md". However, for the part  issueTracker, is not the case: "https://github.com/dgarijo/Widoco/issues". We're curious about the reason behind it.

**Comment by dgarijo** [comment]
@Aidajafarbigloo 
according to https://codemeta.github.io/terms/ the range of `readme` is a URL. We point to the URL of the file with the content.
The issue tracker is not a file, so we point to the service where the issue tracker is located. In this case https://github.com/dgarijo/Widoco/issues.

The reason why we don't point to https://github.com/dgarijo/Widoco/blob/master/README.md as the README is that the URL is a service rendering a file, not the URL of the file itself. For example, if I want to process the file, `https://github.com/dgarijo/Widoco/blob/master/README.md` has many other things that are not the readme in there (all the github links).

**Comment by Aidajafarbigloo** [comment]
Yes, right. Got your point, I appreciate the provided information.

**Comment by dgarijo** [comment]
All right, then I will close the issue.
