### ISSUE TITLE
Extracting metadata from GitLab/GitHub private repositories

### ISSUE THREAD

**Issue by Aidajafarbigloo** [KnowledgeCaptureAndDiscovery/somef#637]
Hello @dgarijo 

Is it possible to extract metadata from GitLab/GitHub private repositories? I tried a private GitHub repo and it doesn't work.

` 19-Apr-24 12:34:04-ERROR-Error: Repository name is private or incorrect `

**Comment by dgarijo** [comment]
I opened #638 to support local folders too. If your question is not answered by my response above, please reopen the issue.
