### ISSUE TITLE
Explore for docker files and notebooks

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/somef#67]
If a repository has a docker file or notebooks, SOMEF should detect them because it's an important piece of information for anyone attempting to understand and use it better.

**Comment by dgarijo** [comment]
I think the easiest way to address this is by doing a git clone of the target repository. This would be a little slower (repo has to be cloned); but gives us access to all files including readme. After somef is done, we can just delete it

**Comment by dgarijo** [comment]
We can probably add a new flag: `-full` `-f` to indicate that we should clone the repo

**Comment by AidanKelley** [comment]
Note: We want to make the links actually resolve to raw.githubusercontent. We need to make this point to a specific commit, rather than just to master, since master will probably change.

**Comment by AidanKelley** [comment]
For dockerfiles use
```sd:hasBuildFile```

For the notebooks use
```sd:hasExecutableNotebook```

**Comment by dgarijo** [comment]
Fixed in latest merge
