### ISSUE TITLE
bug: Invocation and Run shadow each other

### ISSUE THREAD

**Issue by AidanKelley** [KnowledgeCaptureAndDiscovery/somef#69]
Invocation comes from the ML classifiers but run comes from header_analysis. These should have the same name and be merged because they represent the same functionality.

**Comment by dgarijo** [comment]
They are returned with the proper qualification now. Invocation aims at returning just the execution command, while `run` aims at the running instructions. Will be clarified in the [documentation](https://somef.readthedocs.io/en/dev/output/)
