### ISSUE TITLE
run_cli_document in cli.py (and somef package/src/somef/cli.py) is very redundant

### ISSUE THREAD

**Issue by AidanKelley** [KnowledgeCaptureAndDiscovery/somef#71]
It looks to me like this function should be removed, and merged with existing run_cli

**Comment by AidanKelley** [comment]
Also, it actually doesn't appear to be used. If you use the CLI through the __main__.py interface, you'd never invoke this function.

**Comment by dgarijo** [comment]
Please remove and do a PR :)

**Comment by AidanKelley** [comment]
I actually fixed this already. I'm closing the issue.
